app:
  image: ndzenyuy/lumia-app:997e65e
  replicas: 2
  port: 8080

db:
  image: ndzenyuy/lumia-db:997e65e
  port: 3306
  name: accounts
  user: admin
  password: admin123
  storage: 3Gi
  storageClass: gp2
  replicas: 1

ingress:
  host: www.lumiatechs.com
  className: nginx
